# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class TfDrift < Formula
  desc "Go utility to detect, filter, and inspect configuration drift across multi-layered Terraform workspaces."
  homepage "https://github.com/brunobrise/tf-drift"
  version "1.0.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/brunobrise/tf-drift/releases/download/v1.0.0/tf-drift_1.0.0_darwin_amd64.tar.gz"
      sha256 "da5cc9d673afaf2fab74b9d331c8d3f5e6a712a27e9351e16935bc51debfd9b0"

      define_method(:install) do
        bin.install "tf-drift"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/brunobrise/tf-drift/releases/download/v1.0.0/tf-drift_1.0.0_darwin_arm64.tar.gz"
      sha256 "d9994d77e31015c96fcaac9ffb0c01c13bb16262b14223efc6413068a15ac1ea"

      define_method(:install) do
        bin.install "tf-drift"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/brunobrise/tf-drift/releases/download/v1.0.0/tf-drift_1.0.0_linux_amd64.tar.gz"
      sha256 "1569268cbf5b20414ef3511ee2b1e728a664aaa71c822dfd66c4e408a7aed640"
      define_method(:install) do
        bin.install "tf-drift"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/brunobrise/tf-drift/releases/download/v1.0.0/tf-drift_1.0.0_linux_arm64.tar.gz"
      sha256 "523f1bf5b9988f2b20a51ea50b907aab0e05d8d58f8ce4aabe95441a1cdc798e"
      define_method(:install) do
        bin.install "tf-drift"
      end
    end
  end

  test do
    system "#{bin}/tf-drift -version"
  end
end
