# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class TfDrift < Formula
  desc "Go utility to detect, filter, and inspect configuration drift across multi-layered Terraform workspaces."
  homepage "https://github.com/brunobrise/tf-drift"
  version "1.0.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/brunobrise/tf-drift/releases/download/v1.0.0/tf-drift_1.0.0_darwin_amd64.tar.gz"
      sha256 "f3306faa9a09c655d4415195a29e37b412501d6641063d550fc802d4b20a58ca"

      define_method(:install) do
        bin.install "tf-drift"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/brunobrise/tf-drift/releases/download/v1.0.0/tf-drift_1.0.0_darwin_arm64.tar.gz"
      sha256 "a57af8845fafc57099ad6ed5eab8b3d44726bb67e86b2d6051b0d03a424292dd"

      define_method(:install) do
        bin.install "tf-drift"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/brunobrise/tf-drift/releases/download/v1.0.0/tf-drift_1.0.0_linux_amd64.tar.gz"
      sha256 "8776103e097510e67115f56baf86e533b0c808debc9601c828858742a222f505"
      define_method(:install) do
        bin.install "tf-drift"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/brunobrise/tf-drift/releases/download/v1.0.0/tf-drift_1.0.0_linux_arm64.tar.gz"
      sha256 "cb03b102995285ef47137febeb0ba605aaa8f4061b3be21b1c054dd503af5aa0"
      define_method(:install) do
        bin.install "tf-drift"
      end
    end
  end

  test do
    system "#{bin}/tf-drift -version"
  end
end
